zuul:
  prefix: /api
  routes:
    orders-microservice:
      path: /orders-microservice/**
      url: http://localhost:3002
    pricing-microservice:
      path: /pricing-microservice/**
      url: http://localhost:3003
    bulk-order-microservice:
      path: /bulk-order-microservice/**
      url: http://localhost:3001
