CREATE TABLE PRICING
(
id bigint(20) NOT NULL AUTO_INCREMENT,
pcode varchar(255) NOT NULL,
PAYMENT_METHOD varchar(255) NOT NULL,
ORIG_PRICE double NOT NULL,
DISC_PRICE double NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
